[package]
name = "iptui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursive = "0.20.0"
derive_more = "0.99.17"
ifcfg = "0.1.2"
serde = { version = "1.0.197", features = ["derive"] }
